export const AUDIT_SCOPE = {
  FIRM: 'FIRM',
  CLIENT: 'CLIENT',
  ENGAGEMENT: 'ENGAGEMENT',
  DOCUMENT: 'DOCUMENT',
} as const

export type AuditScope = typeof AUDIT_SCOPE[keyof typeof AUDIT_SCOPE]

export const AUDIT_EVENT = {
  // Firm
  FIRM_CREATED: 'FIRM_CREATED',
  FIRM_CHANGED: 'FIRM_CHANGED',
  FIRM_DELETED: 'FIRM_DELETED',
  FIRM_SETTINGS_CHANGED: 'FIRM_SETTINGS_CHANGED',
  FIRM_BRANDING_CHANGED: 'FIRM_BRANDING_CHANGED',
  FIRM_MEMBER_INVITED: 'FIRM_MEMBER_INVITED',
  FIRM_MEMBER_ADDED: 'FIRM_MEMBER_ADDED',
  FIRM_MEMBER_REMOVED: 'FIRM_MEMBER_REMOVED',
  FIRM_MEMBER_ROLE_CHANGED: 'FIRM_MEMBER_ROLE_CHANGED',
  FIRM_CONNECTOR_ATTACHED: 'FIRM_CONNECTOR_ATTACHED',
  FIRM_CONNECTOR_DETACHED: 'FIRM_CONNECTOR_DETACHED',

  // Storage connector
  STORAGE_CONNECTOR_ATTACHED: 'STORAGE_CONNECTOR_ATTACHED',
  STORAGE_CONNECTOR_DETACHED: 'STORAGE_CONNECTOR_DETACHED',

  // Client
  CLIENT_CREATED: 'CLIENT_CREATED',
  CLIENT_CHANGED: 'CLIENT_CHANGED',
  CLIENT_DELETED: 'CLIENT_DELETED',
  CLIENT_SETTINGS_CHANGED: 'CLIENT_SETTINGS_CHANGED',
  CLIENT_CONTACT_CREATED: 'CLIENT_CONTACT_CREATED',
  CLIENT_CONTACT_CHANGED: 'CLIENT_CONTACT_CHANGED',
  CLIENT_CONTACT_DELETED: 'CLIENT_CONTACT_DELETED',
  CLIENT_MEMBER_ADDED: 'CLIENT_MEMBER_ADDED',
  CLIENT_MEMBER_REMOVED: 'CLIENT_MEMBER_REMOVED',
  CLIENT_MEMBER_ROLE_CHANGED: 'CLIENT_MEMBER_ROLE_CHANGED',

  // Engagement
  ENGAGEMENT_CREATED: 'ENGAGEMENT_CREATED',
  ENGAGEMENT_CHANGED: 'ENGAGEMENT_CHANGED',
  ENGAGEMENT_DELETED: 'ENGAGEMENT_DELETED',
  ENGAGEMENT_CLOSED: 'ENGAGEMENT_CLOSED',
  ENGAGEMENT_REOPENED: 'ENGAGEMENT_REOPENED',
  ENGAGEMENT_LOCKED: 'ENGAGEMENT_LOCKED',
  ENGAGEMENT_SETTINGS_CHANGED: 'ENGAGEMENT_SETTINGS_CHANGED',
  ENGAGEMENT_MEMBER_ADDED: 'ENGAGEMENT_MEMBER_ADDED',
  ENGAGEMENT_MEMBER_REMOVED: 'ENGAGEMENT_MEMBER_REMOVED',
  ENGAGEMENT_MEMBER_ROLE_CHANGED: 'ENGAGEMENT_MEMBER_ROLE_CHANGED',
  ENGAGEMENT_FOLDER_ATTACHED: 'ENGAGEMENT_FOLDER_ATTACHED',

  // Document
  DOCUMENT_CREATED: 'DOCUMENT_CREATED',
  DOCUMENT_CHANGED: 'DOCUMENT_CHANGED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_MOVED: 'DOCUMENT_MOVED',
  DOCUMENT_VERSIONED: 'DOCUMENT_VERSIONED',
  DOCUMENT_OPENED: 'DOCUMENT_OPENED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  DOCUMENT_INDEXED: 'DOCUMENT_INDEXED',
  DOCUMENT_FINALIZED: 'DOCUMENT_FINALIZED',
  DOCUMENT_UNLOCKED: 'DOCUMENT_UNLOCKED',
  DOCUMENT_STATUS_CHANGED: 'DOCUMENT_STATUS_CHANGED',
  DOCUMENT_COMMENT_CREATED: 'DOCUMENT_COMMENT_CREATED',
  DOCUMENT_COMMENT_CHANGED: 'DOCUMENT_COMMENT_CHANGED',
  DOCUMENT_COMMENT_DELETED: 'DOCUMENT_COMMENT_DELETED',

  // Document sharing
  DOCUMENT_SHARE_CREATED: 'DOCUMENT_SHARE_CREATED',
  DOCUMENT_SHARE_CHANGED: 'DOCUMENT_SHARE_CHANGED',
  DOCUMENT_SHARE_DELETED: 'DOCUMENT_SHARE_DELETED',
  DOCUMENT_SHARE_VIEWED: 'DOCUMENT_SHARE_VIEWED',
  DOCUMENT_SHARE_DOWNLOADED: 'DOCUMENT_SHARE_DOWNLOADED',
  DOCUMENT_SHARE_REGRANTED: 'DOCUMENT_SHARE_REGRANTED',

  // Onboarding lifecycle
  ONBOARDING_WORKSPACE_INITIALIZED: 'ONBOARDING_WORKSPACE_INITIALIZED',
  ONBOARDING_SUBSCRIBE_COMPLETED: 'ONBOARDING_SUBSCRIBE_COMPLETED',
  ONBOARDING_SUBSCRIBE_SKIPPED: 'ONBOARDING_SUBSCRIBE_SKIPPED',
  ONBOARDING_DRIVE_CONNECTED: 'ONBOARDING_DRIVE_CONNECTED',
  ONBOARDING_PROVISIONING_STARTED: 'ONBOARDING_PROVISIONING_STARTED',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',
  ONBOARDING_DOMAIN_JOINED: 'ONBOARDING_DOMAIN_JOINED',

  // Audit meta
  AUDIT_LOG_EXPORTED: 'AUDIT_LOG_EXPORTED',
} as const

export type AuditEvent = typeof AUDIT_EVENT[keyof typeof AUDIT_EVENT]
