import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireProjectManage } from '@/lib/api/engagement-auth'
import { resolveEngagementConnector } from '@/lib/connectors/resolve-client-connector'
import { getStorageAdapter } from '@/lib/connectors/registry'
import { googleDriveConnector } from '@/lib/google-drive-connector'
import { moveOneDriveFile, renameOneDriveFile } from '@/lib/connectors/adapters/onedrive-file-ops'
import { verifyApprovalToken } from '@/lib/ai/files-agent/approval'
import { agentUserId } from '@/lib/ai/files-agent/agent-identity'
import type { Proposal } from '@/lib/ai/files-agent/tools'
import { audit, AUDIT_EVENT, AUDIT_SCOPE } from '@/lib/audit'
import { safeInngestSend } from '@/lib/inngest/client'
import { logger } from '@/lib/logger'

export const dynamic = 'force-dynamic'

const isOneDrive = (c: { type: string } | null) => c?.type === 'ONEDRIVE'

/** One proposal's outcome, so the UI can show exactly what did and did not happen. */
interface ApplyOutcome {
    proposal: Proposal
    ok: boolean
    error?: string
}

/**
 * POST /api/projects/[projectId]/files-agent/apply
 *
 * Applies proposals the Engagement Lead has approved.
 *
 * ## Three gates, all of which must pass
 *
 * 1. `requireProjectManage` — the caller is the EL or a firm admin, re-checked here rather than
 *    trusted from the propose call.
 * 2. The approval token — these exact proposals were generated by us, for this engagement and
 *    this user, recently, and have not been applied before.
 * 3. Per-operation validation inside the loop — a file that moved or vanished between review and
 *    approval is skipped rather than acted on blindly.
 *
 * ## Attribution
 *
 * Every change is audited as Brio PMO, not as the approving lead. The lead decided; the agent
 * acted. A reader of the Audit tab should be able to tell those apart without knowing this
 * feature exists.
 *
 * Operations run sequentially and independently: one failure does not abort the rest, because a
 * half-applied batch the user cannot see is worse than a fully-reported partial one.
 */
export async function POST(
    request: NextRequest,
    { params }: { params: Promise<{ projectId: string }> },
) {
    try {
        const { projectId } = await params

        const auth = await requireProjectManage(request, projectId)
        if (auth instanceof NextResponse) return auth
        const { user, ctx } = auth

        const body = await request.json().catch(() => null) as {
            token?: unknown
            proposals?: unknown
        } | null

        const token = typeof body?.token === 'string' ? body.token : ''
        const proposals = Array.isArray(body?.proposals) ? body!.proposals as Proposal[] : []

        if (!token || proposals.length === 0) {
            return NextResponse.json({ error: 'Nothing to apply' }, { status: 400 })
        }

        const verdict = verifyApprovalToken({
            token, engagementId: projectId, userId: user.id, proposals,
        })
        if (!verdict.ok) {
            // Deliberately specific: "expired" and "already-used" are things the user can act on,
            // and hiding them behind a generic refusal would make the feature feel broken.
            const message = verdict.reason === 'expired'
                ? 'This review has expired. Run it again to apply these changes.'
                : verdict.reason === 'already-used'
                    ? 'These changes have already been applied.'
                    : 'These changes could not be verified. Run the review again.'
            return NextResponse.json({ error: message, reason: verdict.reason }, { status: 409 })
        }

        const connector = await resolveEngagementConnector(projectId)
        if (!connector) {
            return NextResponse.json({ error: 'No storage connector for this engagement' }, { status: 404 })
        }

        const actorId = agentUserId(ctx.orgId)
        const outcomes: ApplyOutcome[] = []

        // Folders first: a move may target a folder this batch creates, and a destination that
        // does not exist yet would fail for a reason the user cannot interpret.
        const ordered = [
            ...proposals.filter((p) => p.kind === 'folder'),
            ...proposals.filter((p) => p.kind !== 'folder'),
        ]

        for (const proposal of ordered) {
            try {
                if (proposal.kind === 'rename') {
                    const result = isOneDrive(connector)
                        ? await renameOneDriveFile(connector.id, proposal.externalId, proposal.proposedName)
                        : await googleDriveConnector.renameFile(connector.id, proposal.externalId, proposal.proposedName)
                    if (!result) throw new Error('Provider rejected the rename')

                    await prisma.engagementDocument.updateMany({
                        where: { engagementId: projectId, externalId: proposal.externalId },
                        data: { fileName: proposal.proposedName, updatedBy: actorId },
                    })

                    audit(AUDIT_EVENT.DOCUMENT_CHANGED)
                        .firm(ctx.orgId).client(ctx.clientId).engagement(projectId)
                        .actor(actorId).scope(AUDIT_SCOPE.DOCUMENT)
                        .meta({
                            fileName: proposal.proposedName,
                            previousName: proposal.currentName,
                            reason: proposal.reason,
                            viaAgent: true,
                        })
                        .fireAndForget()

                    await safeInngestSend('file.index.requested', {
                        projectId, fileId: proposal.externalId, connectorId: connector.id,
                    })
                }

                if (proposal.kind === 'move') {
                    const result = isOneDrive(connector)
                        ? await moveOneDriveFile(connector.id, proposal.externalId, proposal.destinationFolderId)
                        : await googleDriveConnector.moveFile(connector.id, proposal.externalId, proposal.destinationFolderId)
                    if (!result) throw new Error('Provider rejected the move')

                    await prisma.engagementDocument.updateMany({
                        where: { engagementId: projectId, externalId: proposal.externalId },
                        data: { parentId: proposal.destinationFolderId, updatedBy: actorId },
                    })

                    audit(AUDIT_EVENT.DOCUMENT_MOVED)
                        .firm(ctx.orgId).client(ctx.clientId).engagement(projectId)
                        .actor(actorId).scope(AUDIT_SCOPE.DOCUMENT)
                        .meta({
                            fileName: proposal.fileName,
                            toFolderId: proposal.destinationFolderId,
                            toFolderName: proposal.destinationName,
                            reason: proposal.reason,
                            viaAgent: true,
                        })
                        .fireAndForget()
                }

                if (proposal.kind === 'folder') {
                    const adapter = await getStorageAdapter(connector.id)
                    const parentId = proposal.parentId ?? (await prisma.engagement.findUnique({
                        where: { id: projectId }, select: { connectorRootFolderId: true },
                    }))?.connectorRootFolderId
                    if (!parentId) throw new Error('No parent folder resolved')

                    // findOrCreate rather than create: a batch applied twice, or a folder the user
                    // made themselves in between, should not produce a duplicate.
                    const newId = await adapter.findOrCreateFolder(connector.id, parentId, proposal.name)

                    audit(AUDIT_EVENT.DOCUMENT_CREATED)
                        .firm(ctx.orgId).client(ctx.clientId).engagement(projectId)
                        .actor(actorId).scope(AUDIT_SCOPE.DOCUMENT)
                        .meta({ fileName: proposal.name, parentId, folderId: newId, viaAgent: true })
                        .fireAndForget()
                }

                outcomes.push({ proposal, ok: true })
            } catch (error) {
                logger.warn(`[files-agent] proposal failed: ${(error as Error).message}`)
                outcomes.push({
                    proposal,
                    ok: false,
                    error: 'Could not apply this change',
                })
            }
        }

        return NextResponse.json({
            data: {
                applied: outcomes.filter((o) => o.ok).length,
                failed: outcomes.filter((o) => !o.ok).length,
                outcomes,
            },
        })
    } catch (error) {
        logger.error('[files-agent/apply] POST failed:', error as Error)
        return NextResponse.json({ error: 'Could not apply the changes' }, { status: 500 })
    }
}
