import { serve } from "inngest/next";
import { inngest } from "@/lib/inngest/client";
import {
    revokeProjectSharing,
    revokeByDisabledPersona,
    revokeByMemberPersonaChange,
    revokeByRemovedMember,
    grantPermissionsForNewMember,
    indexFileForSearch,
    indexBatchForSearch,
    scanAndIndexProject,
    populateSandboxSampleFiles,
    reconcileFileDeletion,
    reconcileFolderDeletion,
    migrateWorkspaceRoot,
    platformMaintenanceActivate,
    checkClientFollowUpReminders,
    sendReminderEmail,
    sendRecurringReminderEmails,
    cleanupEngagementReminders,
    cleanupMemberReminders,
    cleanupDocumentReminders,
    purgeDeletedEngagements,
} from "@/lib/inngest/functions";

export const { GET, POST, PUT } = serve({
    client: inngest,
    functions: [
        revokeProjectSharing,
        revokeByDisabledPersona,
        revokeByMemberPersonaChange,
        revokeByRemovedMember,
        grantPermissionsForNewMember,
        indexFileForSearch,
        indexBatchForSearch,
        scanAndIndexProject,
        populateSandboxSampleFiles,
        reconcileFileDeletion,
        reconcileFolderDeletion,
        migrateWorkspaceRoot,
        platformMaintenanceActivate,
        checkClientFollowUpReminders,
        sendReminderEmail,
        sendRecurringReminderEmails,
        cleanupEngagementReminders,
        cleanupMemberReminders,
        cleanupDocumentReminders,
        purgeDeletedEngagements,
    ],
});
