import { parseChatReply } from './engagement-chat'

/**
 * Renders an on-screen conversation as a Markdown transcript.
 *
 * ## Why this exists
 *
 * A conversation is lost on refresh — only the questions persist, deliberately, because answers
 * embed engagement data and go stale within a day. Export is the alternative to storing them: the
 * user keeps what is worth keeping, once, by choosing to.
 *
 * ## Why it carries a staleness footer
 *
 * The footer is not boilerplate. Every answer is true of the moment it was generated — "4 documents
 * unscheduled" stops being true the moment someone schedules one. A transcript pasted into a client
 * update three days later would state those figures as current with nothing to say otherwise. The
 * footer is the only thing travelling with the text that can say so.
 *
 * No `server-only`: this runs in the panel, from messages already rendered.
 */

export interface TranscriptMessage {
    role: 'user' | 'assistant'
    content: string
    /** True for an answer the user stopped mid-stream; noted in the transcript rather than hidden. */
    stopped?: boolean
}

export interface TranscriptMeta {
    engagementName?: string | null
    clientName?: string | null
    /** Defaults to now; injectable so tests are not time-dependent. */
    generatedAt?: Date
}

function formatStamp(d: Date): string {
    return d.toLocaleString(undefined, {
        day: 'numeric', month: 'long', year: 'numeric',
        hour: '2-digit', minute: '2-digit',
    })
}

/**
 * Builds the transcript. Returns an empty string when there is nothing settled to export.
 *
 * Skips the trailing empty assistant turn that exists while a reply is still streaming — exporting
 * mid-answer would otherwise produce a question with a blank answer under it.
 */
export function buildChatTranscript(
    messages: readonly TranscriptMessage[],
    meta: TranscriptMeta = {},
): string {
    const settled = messages.filter((m) => m.content.trim().length > 0)
    if (settled.length === 0) return ''

    const title = meta.engagementName?.trim() || 'this engagement'
    const subtitleParts = [
        meta.clientName?.trim() || null,
        formatStamp(meta.generatedAt ?? new Date()),
    ].filter(Boolean)

    const lines: string[] = [
        `# Brio — ${title}`,
        subtitleParts.join(' · '),
        '',
    ]

    for (const m of settled) {
        if (m.role === 'user') {
            lines.push(`**Q:** ${m.content.trim()}`, '')
        } else {
            // Parsed, so the follow-up sentinel never reaches the transcript — the same reason
            // per-answer Copy parses rather than copying raw stream text.
            const answer = parseChatReply(m.content).answer.trim()
            if (answer) {
                // Marked, because a transcript is pasted into client updates and notes: a stopped
                // answer looks complete once it leaves the chat, and a half-answer about an
                // engagement presented as whole is exactly the failure this file's footer guards
                // against elsewhere.
                lines.push(m.stopped ? `${answer}\n\n_[stopped — incomplete answer]_` : answer, '')
            }
        }
    }

    lines.push(
        '---',
        'Generated by Brio from engagement data at the time of asking. Figures may have changed since.',
    )

    return lines.join('\n')
}
