export const AUDIT_EVENT_TYPES = [
  // Firm lifecycle
  'FIRM_CREATED', 'FIRM_CHANGED', 'FIRM_DELETED', 'FIRM_SETTINGS_CHANGED', 'FIRM_BRANDING_CHANGED',
  'FIRM_MEMBER_INVITED', 'FIRM_MEMBER_ADDED', 'FIRM_MEMBER_REMOVED', 'FIRM_MEMBER_ROLE_CHANGED',
  'FIRM_CONNECTOR_ATTACHED', 'FIRM_CONNECTOR_DETACHED',
  // Client lifecycle
  'CLIENT_CREATED', 'CLIENT_CHANGED', 'CLIENT_DELETED', 'CLIENT_SETTINGS_CHANGED',
  'CLIENT_CONTACT_CREATED', 'CLIENT_CONTACT_CHANGED', 'CLIENT_CONTACT_DELETED',
  'CLIENT_MEMBER_ADDED', 'CLIENT_MEMBER_REMOVED', 'CLIENT_MEMBER_ROLE_CHANGED',
  // Engagement lifecycle
  'ENGAGEMENT_CREATED', 'ENGAGEMENT_CHANGED', 'ENGAGEMENT_DELETED', 'ENGAGEMENT_CLOSED',
  'ENGAGEMENT_REOPENED', 'ENGAGEMENT_LOCKED', 'ENGAGEMENT_SETTINGS_CHANGED',
  'ENGAGEMENT_MEMBER_ADDED', 'ENGAGEMENT_MEMBER_REMOVED', 'ENGAGEMENT_MEMBER_ROLE_CHANGED',
  'ENGAGEMENT_FOLDER_ATTACHED',
  // Document lifecycle
  'DOCUMENT_CREATED', 'DOCUMENT_CHANGED', 'DOCUMENT_DELETED', 'DOCUMENT_MOVED',
  'DOCUMENT_VERSIONED', 'DOCUMENT_OPENED', 'DOCUMENT_DOWNLOADED', 'DOCUMENT_INDEXED',
  'DOCUMENT_FINALIZED', 'DOCUMENT_UNLOCKED', 'DOCUMENT_STATUS_CHANGED',
  'DOCUMENT_COMMENT_CREATED', 'DOCUMENT_COMMENT_CHANGED', 'DOCUMENT_COMMENT_DELETED',
  // Document sharing
  'DOCUMENT_SHARE_CREATED', 'DOCUMENT_SHARE_CHANGED', 'DOCUMENT_SHARE_DELETED',
  'DOCUMENT_SHARE_VIEWED', 'DOCUMENT_SHARE_DOWNLOADED', 'DOCUMENT_SHARE_REGRANTED',
  // Onboarding
  'ONBOARDING_WORKSPACE_INITIALIZED', 'ONBOARDING_SUBSCRIBE_COMPLETED', 'ONBOARDING_SUBSCRIBE_SKIPPED',
  'ONBOARDING_DRIVE_CONNECTED', 'ONBOARDING_PROVISIONING_STARTED', 'ONBOARDING_COMPLETED',
  'ONBOARDING_DOMAIN_JOINED',
  // Audit meta
  'AUDIT_LOG_EXPORTED',
] as const

export type AuditEventType = typeof AUDIT_EVENT_TYPES[number]

export function isValidAuditEventType(value: string): value is AuditEventType {
  return (AUDIT_EVENT_TYPES as readonly string[]).includes(value)
}
